# Generated by Django 5.0.7 on 2024-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_clients_article_member'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='articles',
            field=models.ManyToManyField(to='article.article'),
        ),
    ]
