services:
  selling_back:
    image: koire0312/my-django-app
    container_name: selling_back
    restart: always
    depends_on:
      - selling_admin_back
    networks:
      - applications_network
    environment:
      DJANGO_SETTINGS_MODULE: myproject.settings
      DEBUG: 'False'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: 3306
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    ports:
      - "8080:8080"
