services:
  selling_back:
    image: koire0312/my-django-app
    container_name: selling_back
    restart: always
    depends_on:
      - selling_admin_back
    networks:
      - applications_network
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: 3307
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

