version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: EMVCCgtMxYeLMRSEnfPNWlBIvFxZvQMu
    volumes:
      - db-data:/var/lib/mysql

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:EMVCCgtMxYeLMRSEnfPNWlBIvFxZvQMu@db:3306/railway
    depends_on:
      - db

volumes:
  db-data:

