services:
  selling_admin_back:
    image: mysql:latest
    container_name: selling_admin_back
    command:
      --default-authentication-plugin = mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: selling_db
      MYSQL_USER: root
      MYSQL_PASSWORD: koire
    networks:
      - applications_network

  adminer:
    image: adminer:4.8.1-standalone
    container_name: selling_db
    restart: always
    networks:
      - applications_network

networks:
  applications_network:
    external: true
    name: applications_network
#  web:
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    environment:
#      - DATABASE_URL=mysql://root:koire:3307/selling_db
#    depends_on:
#      - db
#
#volumes:
#  db-data:

