services:
  selling_admin_back:
    image: mysql:latest
    container_name: selling_admin_back
    command:
      --default-authentication-plugin = mysql_native_password
    restart: always
    environment:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: 3306
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    networks:
      - selling_admin_back_network

  adminer:
    image: adminer:4.8.1-standalone
    container_name: selling_db
    restart: always
    networks:
      - selling_admin_back_network

networks:
  selling_admin_back_network:
    external: true
    name: selling_admin_back_network
#  web:
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    environment:
#      - DATABASE_URL=mysql://root:koire:3307/selling_db
#    depends_on:
#      - db
#
#volumes:
#  db-data:

