# Generated by Django 5.1.7 on 2025-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createDate', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('logo', models.ImageField(default='media/photos/logo.jpeg', upload_to='photos/')),
            ],
        ),
    ]
