# Generated by Django 5.0.7 on 2024-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createDate', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('logo', models.ImageField(default='default_logo.png', upload_to='photos/')),
                ('logo_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
