# Generated by Django 5.0.7 on 2024-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
