# Generated by Django 5.1 on 2025-02-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_logo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(default='media/photos/logo.jpeg', upload_to='photos/'),
        ),
    ]
