# Generated by Django 5.1.7 on 2025-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('CLIENT', 'Client')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
