# Generated by Django 5.1 on 2024-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='privileges',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('CLIENT', 'Client')], max_length=20),
        ),
    ]
