# Generated by Django 5.0.7 on 2024-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privilegies', '0002_remove_privilegies_role'),
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='privileges',
            field=models.ManyToManyField(related_name='privileges', to='privilegies.privilegies'),
        ),
    ]
