# Generated by Django 5.0.7 on 2024-08-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('logo', models.ImageField(default='default_logo.png', upload_to='photos/')),
                ('logo_name', models.CharField(blank=True, max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('logo', models.ImageField(default='default_logo.png', upload_to='photos/')),
                ('logo_name', models.CharField(blank=True, max_length=255)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organisation.organisation')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
