# Generated by Django 5.1.7 on 2025-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
