# Generated by Django 5.1 on 2024-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
