# Generated by Django 5.1 on 2025-02-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_remove_utilisateur_logo_name_alter_utilisateur_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='logo',
            field=models.ImageField(default='media/photos/logo.jpeg', upload_to='photos/'),
        ),
    ]
