# Generated by Django 5.0.7 on 2024-07-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
