# Generated by Django 5.0.7 on 2024-08-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_articles'),
        ('organisation', '0002_alter_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organisation.organisation'),
        ),
    ]
