# Generated by Django 5.0.7 on 2024-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_logo_alter_member_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='logo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
