# Generated by Django 5.1 on 2024-08-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('logo', models.ImageField(default='default_logo.png', upload_to='photos/')),
                ('logo_name', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.categorie')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.member')),
            ],
        ),
    ]
