# Generated by Django 5.0.7 on 2024-07-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('member', '0002_remove_member_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='clients',
        ),
        migrations.AddField(
            model_name='article',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
