# Generated by Django 5.1 on 2024-08-16 23:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='logo_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='default_logo.png', max_length=255, verbose_name='image'),
        ),
    ]
