# Generated by Django 5.1 on 2024-08-17 14:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_logo_name_alter_article_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='media/photos/logo.jpeg', max_length=255, verbose_name='image'),
        ),
    ]
