# Generated by Django 5.0.7 on 2024-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='logo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
