# Generated by Django 5.1 on 2025-02-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_urlpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='logo',
            field=models.ImageField(default='media/photos/logo.jpeg', upload_to='photos/'),
        ),
    ]
