# Generated by Django 5.1 on 2025-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='logo',
            field=models.ImageField(default='photos/logo.jpeg', upload_to='photos/'),
        ),
    ]
