# Generated by Django 5.0.7 on 2024-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilegies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.CharField(choices=[('ADD', 'Add'), ('DELETE', 'Delete'), ('UPDATE', 'Update'), ('ALL', 'All'), ('FIND', 'Find')], default='FIND', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
