name: deploy selling Back
on: [push]
jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 2222
          script: |
            mkdir -p /opt/applications/e_selling_admin_back/
            ls -al /opt/applications/e_selling_admin_back/

  generate-image:
    name: generate-image
    needs: ["create-folder"]  # Correct placement of 'needs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: snok/latest-python-versions@v1
        id: get-python-versions
        with:
          min-version: 3.7
          max-version: 3.10
          include-prereleases: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-django-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login
