name: deploy selling Back
on: [push]
jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 2222
          script: |
            mkdir -p /opt/applications/e_selling_admin_back/
            ls -al /opt/applications/e_selling_admin_back/

  generate-image:
    name: generate-image
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Assure-toi d'utiliser la version correcte

      - name: Set up Python version
        uses: actions/setup-python@v2  # Remplace avec l'action officielle pour configurer Python
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-django-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-django-app:latest koire0312/my-django-app:latest
          docker push koire0312/my-django-app:latest
